### ISSUE TITLE
Kibana server 6.2.3 fails to start

### ISSUE THREAD

**Issue by papou1971** [nreese/kibana-time-plugin#38] opened 2018-05-18 08:14 UTC
I try to install the plugin on my Kibana 6.2.3 / linux VM  and i have an error due to missing ressources.
So i try now to a desktop windows PC with the same Kibana version 6.2.3.
I succeeded to install the plugin but i have the same error that over Linux VM when i start the kibana server 👍 
Here the stack trace :
{"type":"error","@timestamp":"2018-05-18T07:58:21Z","tags":["fatal"],"pid":10532,"level":"fatal","error":{"message":"Optimizations failure.\n   6433 modules\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/kibana-time-plugin/public/timeController.js\n    Module not found: Error: Can't resolve 'ui/timepicker/quick_ranges' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   6433 modules\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ../plugins/kibana-time-plugin/public/timeController.js\n    Module not found: Error: Can't resolve 'ui/timepicker/quick_ranges' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\src\\optimize\\base_optimizer.js:245:27)\n    at D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\src\\optimize\\fs_optimizer.js:37:30\n    at onCompiled (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:241:12)\n    at applyPluginsAsync.err (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:514:14)\n    at next (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compiler.<anonymous> (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at compilation.seal.err (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:662:11)\n    at next (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compilation.<anonymous> (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\index.js:244:6)\n    at Compilation.applyPluginsAsyncSeries (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at self.applyPluginsAsync.err (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:657:10)\n    at next (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compilation.<anonymous> (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\extract-text-webpack-plugin\\dist\\index.js:275:11)\n    at Compilation.applyPluginsAsyncSeries (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at sealPart2 (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:653:9)\n    at next (D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\node_modules\\extract-text-webpack-plugin\\dist\\index.js:244:13"},"message":"Optimizations failure.\n   6433 modules\n    \n    ERROR in ../plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\n    \n    ERROR in ../plugins/kibana-time-plugin/public/timeController.js\n    Module not found: Error: Can't resolve 'ui/timepicker/quick_ranges' in 'D:\\DEV\\Elastic\\kibana\\kibana-6.2.3-windows-x86_64\\plugins\\kibana-time-plugin\\public'\n"}

**Comment by retsuca** [comment] 2018-06-13 00:23
i am having same problem on linux machine. I think it is not related to os.

**Comment by nreese** [comment] 2018-06-13 01:14
How are you installing the plugin? It is not running because the plugin is trying to import `ui/template_vis_type/template_vis_type`. That file was removed in Kibana 6.0 and the plugin has been updated to accomidate this. Are you trying to run a 5.x version in Kibana 6.2? That will not work.

**Comment by retsuca** [comment] 2018-06-13 12:42
Ah i am sorry :( 
I think i was too sleepless to notice diffrence. I did get manage to overcome this as you said with correct. plugin version.

My error was this:
`Error: Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}]]
http://errors.angularjs.org/1.6.5/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%5D (http://rapor.gsi365.com/bundles/vendors.bundle.js?v=16627:58)
    at window.onerror (http://rapor.gsi365.com/bundles/commons.bundle.js?v=16627:1:504052)`

Should i open new issue?

**Comment by nreese** [comment] 2018-06-13 12:56
> Should i open new issue?

Yes.

I will close this issue and if you could create a new issue that contains the steps taken to reproduce that would be helpful

**Closed as completed by nreese** 2018-06-13 12:56 UTC
